-- Elune Prime. Probe 2026-09-18 (Haranir Guardian, spec 104, hero 24).
-- SBA: Bear Form, Convoke, Lunar Beam, Mangle, MotW, Moonfire, Raze, Swipe, Thrash, Rake, Rip.
-- Non-SBA combat gets a bind. Recover and World are click-only. Ctrl-M4 stays camera.
-- Thorn Bloom / Rootwalking live on Attack (Shift-E / Alt-E), not a Thorn family.
SuperBinds.RegisterProfile({
  name="Elune Prime", class="DRUID", familyMode="elune-prime", spec=104, hero=24, default=true,
  useBlizzardSBA=false, form="caster", nativeForm="bear",
  appliedNote="Elune Prime: E attack  Q disrupt  M5 heal  wheel forms  M4 dash  C protect  R empower  X mount. Shift-E Thorn  Alt-E Rootwalking. Ctrl-wheel zooms. Ctrl-M4 stays camera.",
  spellIds={
    ["Thorn Bloom"]=1237885,
    ["Rootwalking"]=1238686,
    ["Rootwalking: Return"]=1238695,
  },
  ground={"Thorn Bloom"},
  actionOverride={"Rootwalking"},
  forms={
    cat={spells={768}},
    bear={spells={5487}},
    travel={spells={783,33943,40120,1066}},
  },
  actionBars={
    caster={page=1},
    cat={bonus=1},
    bear={bonus=3},
    travel={page=1,use="caster"},
  },
  neverSuggest={
    "Cat Form","Bear Form","Travel Form","Moonkin Form","Treant Form","Stag Form",
    768,5487,783,24858,197625,33891,114282,33943,40120,1066,
    1850,77761,77764,106898,
  },
  neverBind={}, exclude={}, sculptures={},
  rotation={
    caster={
      {spell={8921,1253582},auraMissing=true,dot=8,ranged=true},
      {spell={5176,190984},fallback=true},
    },
    bear={
      {spell={77758,106832}},
      {spell={33917}},
      {spell={8921,1253582},auraMissing=true,dot=16,ranged=true},
      {spell={204066}},
      {spell={400254},powerType=1,minPower=40},
      {spell={213771,106785},fallback=true},
    },
    cat={
      {spell={1822},auraMissing=true,dot=12},
      {spell={1079}},
      {spell={22568},powerType=4,minPower=5},
      {spell={5221},fallback=true},
    },
    travel={},
  },
  families={
    {tag="E",title="Attack · E",caption="ATTACK",
      bars={
        caster={slot=1,key="E",spell={8921},label="Moonfire",target="harm"},
        cat={slot=1,key="E",spell={5221},label="Shred",target="harm"},
        bear={slot=1,key="E",sba=true,label="Assisted Rotation"},
      },
      items={
        {slot=5,bindKey="SHIFT-E",key="Shift-E",allBars=true,label="Thorn Bloom",target="cursor",
          spell={1237885,"Thorn Bloom"},
          macro={"SBThorn",7491039,"#showtooltip Thorn Bloom\n/cast [@cursor] Thorn Bloom"}},
        {spell={1238686,"Rootwalking",1238695,"Rootwalking: Return"},label="Rootwalking",
          bindKey="ALT-E",key="Alt-E",
          covers={"Rootwalking","Rootwalking: Return"},requires="Rootwalking",
          note="Haranir · cancels form"},
        {spell={213771,106785,213764},label="Swipe",target="harm",note="SBA · click"},
        {spell={77758,106832},label="Thrash",target="harm",note="SBA · click"},
      }},
    {tag="Q",title="Disrupt · Q",caption="DISRUPT",
      bars={
        caster={slot=2,key="Q",spell={339},label="Entangling Roots",target="harm"},
        cat={slot=2,key="Q",spell={5215},label="Prowl"},
        bear={slot=2,key="Q",spell={6795},label="Growl"},
      },
      items={
        {spell={106839},label="Skull Bash",bindKey="SHIFT-Q",target="harm",note="interrupt"},
        {spell={132469},label="Typhoon",bindKey="CTRL-Q",note="knockback"},
        {spell={102793},label="Ursol's Vortex",bindKey="ALT-Q",target="cursor",note="pull"},
        {spell={2908},label="Soothe",bindKey="CTRL-SHIFT-Q",target="harm",note="enrage off"},
      }},
    {tag="M5",title="Heal · M5",caption="HEAL",
      bars={
        caster={slot=8,key="M5",bindKey="BUTTON5",spell={8936},label="Regrowth",target="help"},
        cat={slot=8,key="M5",bindKey="BUTTON5",spell={8936},label="Regrowth",target="help"},
        bear={slot=8,key="M5",bindKey="BUTTON5",spell={22842},label="Frenzied Regeneration"},
      },
      items={
        {spell={22842},label="Frenzied Regeneration",note="bear heal · click"},
        {spell={8936},label="Regrowth",target="help",note="click"},
      }},
    {tag="T",title="Forms · wheel",caption="FORMS",
      bar={slot=3,key="WheelUp",bindKey="MOUSEWHEELUP",spell={5487},label="Bear Form",allBars=true},
      items={
        {slot=4,key="WheelDown",bindKey="MOUSEWHEELDOWN",spell={768},label="Cat Form",allBars=true},
        {slot=6,key="Shift-WheelDown",bindKey="SHIFT-MOUSEWHEELDOWN",spell={783},label="Travel Form",allBars=true},
      }},
    {tag="M4",title="Move · M4",caption="MOVE",
      bar={slot=10,key="M4",bindKey="BUTTON4",spell={1850},label="Dash",allBars=true},
      items={
        {spell={102401},label="Wild Charge",bindKey="SHIFT-BUTTON4",note="gap closer"},
        {spell={77761,77764,106898},label="Stampeding Roar",bindKey="ALT-BUTTON4",
          note="group speed · Ctrl-M4 is camera"},
      }},
    {tag="C",title="Protect · C",caption="PROTECT",
      bars={
        caster={slot=7,key="C",spell={22812},label="Barkskin"},
        cat={slot=7,key="C",spell={22812},label="Barkskin"},
        bear={slot=7,key="C",spell={192081},label="Ironfur"},
      },
      items={
        {spell={61336},label="Survival Instincts",bindKey="SHIFT-C",note="big wall"},
        {spell={22812},label="Barkskin",note="wall · click"},
      }},
    {tag="R",title="Empower · R",caption="EMPOWER",
      bars={
        caster={slot=9,key="R",spell={5176},label="Wrath",target="harm"},
        cat={slot=9,key="R",spell={22568},label="Ferocious Bite",target="harm"},
        bear={slot=9,key="R",spell={204066},label="Lunar Beam",target="harm"},
      },
      items={
        {spell={102558},label="Incarnation: Guardian of Ursoc",bindKey="SHIFT-R",note="burst"},
        {spell={319454,108291,"Heart of the Wild"},label="Heart of the Wild",bindKey="CTRL-R",note="off-spec window"},
        {spell={400254},label="Raze",target="harm",note="SBA · click"},
        {spell={204066},label="Lunar Beam",target="harm",note="SBA · click"},
        {spell={391528,323764,"Convoke the Spirits"},label="Convoke the Spirits",note="SBA · click"},
      }},
    {tag="X",title="Travel · X",caption="TRAVEL",
      items={
        {bindKey="X",key="X",macrotext="/dismount [mounted]\n/run if not IsMounted() and not InCombatLockdown() then C_MountJournal.SummonByID(0) end",label="Favorite mount",iconFile=132250},
      }},
    {tag="BUF",title="Buffs · click",caption="BUFFS",
      items={
        {spell={1126},label="Mark of the Wild",note="SBA · click"},
      }},
    {tag="+",title="Recover · click",caption="RECOVER",
      items={
        {spell={20484,"Rebirth"},label="Rebirth",target="help",note="combat rez"},
        {spell={50769},label="Revive",note="out of combat"},
        {spell={2782},label="Remove Corruption",target="help",note="dispel"},
        {spell={18960},label="Teleport: Moonglade"},
        {itemID=6948,label="Hearthstone"},
      }},
    {tag="WLD",title="World · click",caption="WORLD",autoFill="rest",
      items={
        {spell={"Anomaly Detection Mark I"},label="Anomaly Detection Mark I"},
        {spell={"Find High-Value Beasts"},label="Find High-Value Beasts"},
        {spell={"Mechanism Bypass"},label="Mechanism Bypass"},
        {spell={"Overload Herbs"},label="Overload Herbs"},
        {spell={"Recuperate"},label="Recuperate"},
        {spell={"Revive Battle Pets"},label="Revive Battle Pets"},
        {spell={"Sharpen Your Knife"},label="Sharpen Your Knife"},
        {spell={"Skyriding Flight Style"},label="Skyriding Flight Style"},
        {spell={"Skyriding"},label="Skyriding"},
        {spell={"Warbands"},label="Warbands"},
      }},
  },
  hardware={
    BUTTON5={slot=8}, BUTTON4={slot=10},
    ["SHIFT-BUTTON4"]={spell={102401}},
    ["ALT-BUTTON4"]={spell={77761,77764,106898}},
    MOUSEWHEELUP={slot=3}, MOUSEWHEELDOWN={slot=4},
    ["SHIFT-MOUSEWHEELDOWN"]={slot=6},
  },
  reserved={
    ["CTRL-MOUSEWHEELUP"]="camera zoom in",["CTRL-MOUSEWHEELDOWN"]="camera zoom out",
    ["CTRL-BUTTON4"]="camera zoom",["CTRL-BUTTON5"]="camera zoom",
    NUMPADPLUS="camera zoom in",NUMPADMINUS="camera zoom out",
  },
  camera={
    ["CTRL-MOUSEWHEELUP"]="CAMERAZOOMIN",["CTRL-MOUSEWHEELDOWN"]="CAMERAZOOMOUT",
    NUMPADPLUS="CAMERAZOOMIN",NUMPADMINUS="CAMERAZOOMOUT",
  },
  macros={},
  barBinds={
    E="ACTIONBUTTON1",Q="ACTIONBUTTON2",C="ACTIONBUTTON7",R="ACTIONBUTTON9",
    BUTTON5="ACTIONBUTTON8",BUTTON4="ACTIONBUTTON10",
    MOUSEWHEELUP="ACTIONBUTTON3",MOUSEWHEELDOWN="ACTIONBUTTON4",
    ["SHIFT-MOUSEWHEELDOWN"]="ACTIONBUTTON6",
  },
  theme={brass={.65,.51,.28},accent={.35,.65,.9},
    endcap="Interface\\AddOns\\SuperBinds\\Media\\ShamanEndcap.tga",
    endcapWidth=70,endcapHeight=120,
    endcapHorde="Interface\\AddOns\\SuperBinds\\Media\\DruidEndcap_horde.tga",
    endcapHordeWidth=90,endcapHordeHeight=120,
    endcaps={
      bear={path="Interface\\AddOns\\SuperBinds\\Media\\DruidEndcap_bear.tga",width=80,height=120,leftIn=26},
      cat={path="Interface\\AddOns\\SuperBinds\\Media\\DruidEndcap_cat.tga",width=80,height=120,leftIn=26},
      travel={path="Interface\\AddOns\\SuperBinds\\Media\\DruidEndcap_travel.tga",width=80,height=120,leftIn=26},
    }},
})
